#!/bin/bash
if [[ "$1" == *"d"* ]]
then
	/opt/cisco/anyconnect/bin/vpn -s disconnect
	exit
fi

filename="$HOME/bin/.resources/pass"
line=$(head -n 1 $filename)
printf "0\nrgli2\n"$line | /opt/cisco/anyconnect/bin/vpn -s connect https://vpn.cites.illinois.edu
